### ISSUE TITLE
Update to owl 2.x

### ISSUE THREAD

**Issue by sdegueldre** [Coding-Dodo/OWL-JavaScript-Project-Starter#5]
Hello, I was taking a look at Owl's dependents on github (https://github.com/odoo/owl/network/dependents?dependent_type=REPOSITORY) and it looks like a lot of people are using your owl project starter to build apps using owl (nice!)

in Odoo 16.0 we've migrated to owl 2.x which has changed quite a bit (for the better) https://github.com/odoo/owl/blob/master/CHANGELOG.md

I just thought I'd let you know in case you'd like to update your guide and this template project, as owl 1 is basically in maintenance-only mode and will probably be officially unsupported two years from now, and it looks like you're getting quite a few hits from people trying to learn owl, it would probably be better for them if they learned owl 2 straight away.

If you don't have the time to invest in this, that would be perfectly understandable, it's already great to have people from the community writing guides since we often don't have the time to do this ourselves. With owl 2 we've made an effort to improve the official documentation, both on the owl repo and in the odoo docs, you can check out this tutorial for inspiration: https://www.odoo.com/documentation/master/developer/howtos/discover_js_framework.html

Have a nice day :)

**Comment by PhilDL** [comment]
Thank you for reaching out and great job on the new docs (also great job on OWL 2)!

Unfortunately, an extensive series of tutorials are about how to write a complete app in OWL1, that uses this template. 
Last year I tried to begin migration but the loss of the Router and Store made the effort bigger than I imagined.

So I will leave it like that for now (because my tutorial series would break otherwise 😞) but add **an explicit message telling people it's OWL 1** and redirect them to another starter I will make. 

I actually already made one some time ago with OWL 2 https://github.com/Coding-Dodo/OWL-Vite-TypeScript-Tailwind-Starter using Vite as a bundler but it's opinionated and uses TypeScript and Tailwind so I will do another one.

_I will keep this issue open while I work on it._

**Comment by sdegueldre** [comment]
Using the new reactivity the store is pretty easy to replicate (see https://github.com/odoo/owl/blob/master/doc/reference/reactivity.md#store)

We thought the router was something that wasn't universally needed (we didn't use it in Odoo for example) so we thought we'd save ourselves the maintenance burden and just let people implement it in user space. If it would help you I may write a router as a separate package and publish it on npm when I have some free time on a weekend.

I think just telling people the guide is no longer up to date is probably good enough, it's nice that there still exists some documentation for owl 1.x anyway since it's deployed in Odoo 14 and quite a few people still use that version. Thanks!

**Comment by PhilDL** [comment]
Thank you, but I don't want to waste your time. Back in the day when OWL 2 was in beta, I published a gist that combine OWL and Navigo JS Library https://gist.github.com/PhilDL/ae3030e3c68b741a5d4485023014edf4 to have a similar Router API, so I think I will continue on that without bothering you.

I updated the README to mention the depreciation and linked it to a new Starter Repository https://github.com/Coding-Dodo/OWL2-JavaScript-Project-Starter
